# Generated by Django 3.2 on 2023-02-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
