from django.db import models

from store.models import Customer, Order

# Create your models here.


class Currency:
    GBP = 'gbp'


class Payment(models.Model):
    """Save the stripe PaymentIntent id locally incase we need to refer
       back to it later. """

    # this is the id generated by stripe
    payment_intent_id = models.CharField(
        blank=False, max_length=100)  # check stripe id max_length
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    # amount in lowest demonination, for £GBP, this would be pennies
    # e.g. £5.99 would be saved as 599
    amount = models.IntegerField()
    currency = models.CharField(
        choices=((Currency.GBP, "GBP (£)"),), max_length=10)
    order = models.OneToOneField(Order, on_delete=models.CASCADE)

    complete = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def display_amount(self):
        return self.amount / 100
